name: CRON_SCRAPE
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  container-cron-job:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.29.0-focal
    steps:
      - name: Installing Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run PW Scraper
        run: |
          python pw_scrape.py
