name: CRON_SCRAPE
on:
  # push:
  #   branches:
  #     - "feat/notion-db-git-cron"
  schedule:
    - cron: '*/30 * * * *'
jobs:
  container-cron-job:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.29.0-focal
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"
      - name: Installing Packages
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Run PW Scraper
        run: |
          python pw_scrape.py
        env:
          NOTION_DB_SCRAPE_ID: ${{ vars.NOTION_DB_SCRAPE_ID }}
          NOTION_DB_RESULTS_ID: ${{ vars.NOTION_DB_RESULTS_ID }}
          NOTION_API_LINK: ${{ vars.NOTION_API_LINK }}
